services:
  mindbox.devschool.reliability:
    image: mindbox.devschool.reliability
    build:
      context: .
      dockerfile: Mindbox.DevSchool.Reliability/Dockerfile
    ports:
      - "5013:5013"